spring:
  application:
    name: business-service
  profiles:
    active: live  
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtp
    username: ${emailUsername}
    password: ${emailPwd}
    smtp:
      auth: true
      starttls: true

configuration:
  projectName: business-service
server:
  port: 9081
  contextPath: /tr/api/businessservice

logging:
  level:
    org.springframework.security: DEBUG

security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/

com:
  traderocket:
    businessservice:
      config:
        message: Hello Trade Rocket Business Service local (3)!

mail:
  aes:
    key: need tobe change
  verification:
    url: http://localhost:9081/tr/api/businessservice/email/confirmation
    
ldap:
  ldapUrl: ldap://127.0.0.1:10389
  base: dc=example,dc=com
  userDn: uid=admin,ou=system
  userPassword: secret
  password:
    length: 8
  
tfa:
  qrPrefix: https://chart.googleapis.com/chart?chs=200x200&chld=M%%7C0&cht=qr&chl=
  appName: SpringRegistration

pv1:
  autolink:
    timeout: 3600
