debug: true

spring:
  application:
    name: web-portal
  aop:
    proxy-target-class: true

server:
  port: 8083
  contextPath: ${contextPath}
  session:
    timeout: 180000

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: ${authRootUrl}/tr/oauth/token
      userAuthorizationUri: ${authRootUrl}/tr/oauth/authorize
      clientId: trclient
      clientSecret: trclientpassword
      access-token-validity-seconds: 1800000
      #added on 4/26/2017
      pre-established-redirect-uri: ${webPortalRootUrl}/traderocket/login
      registered-redirect-uri: ${authRootUrl}/tr/login1
      use-current-uri: false
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9081/tr/api/businessservice/email
    users:
      path: /users/**
      url: http://localhost:9999/tr/api/accesscontrolservice/users
    links:
      path: /links/**
      url: http://localhost:9081/tr/api/businessservice/links
    user:
      path: /user/**
      url: http://localhost:9080/tr/user
    programs:
      path: /programs/**
      #url: http://localhost:1880/getFlowsWithStart
      #url: http://localhost:1880
      url: ${noderedRootUrl}
    #oauth:
      #path: /oauth/token/**
      #url: http://localhost:9080/tr/oauth/token
    #authorize:
      #path: /oauth/authorize/**
      #url: http://localhost:9080/tr/oauth/authorize
    login:
      path: /login/**
      url: ${authRootUrl}/tr/login

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
